export const songs = [
  {
    id: 1,
    name: "Smoke Some Weed",
    artist: "Ice Cube",
    image: "https://upload.wikimedia.org/wikipedia/en/a/a6/Laughnowcube.jpg",
    genre: "Rap",
    album: "Laugh Now, Cry Later",
  },
  {
    id: 2,
    name: "It Was A Good Day",
    artist: "Ice Cube",
    image:
      "https://upload.wikimedia.org/wikipedia/en/8/8e/Ice_Cube_-_The_Predator_-_Album_Cover.jpg",
    genre: "Rap",
    album: "The Predator",
  },
  {
    id: 3,
    name: "Chop Suey!",
    artist: "System of A Down",
    image: "https://upload.wikimedia.org/wikipedia/en/6/64/SystemofaDownToxicityalbumcover.jpg",
    genre: "Nu Metal",
    album: "Toxicity",
  },
  {
    id: 4,
    name: "Toxicity!",
    artist: "System of A Down",
    image: "https://upload.wikimedia.org/wikipedia/en/6/64/SystemofaDownToxicityalbumcover.jpg",
    genre: "Nu Metal",
    album: "Toxicity",
  },
  {
    id: 5,
    name: "I'm Shady",
    artist: "Eminem",
    image: "https://upload.wikimedia.org/wikipedia/en/3/35/Eminem_-_The_Slim_Shady_LP_CD_cover.jpg",
    genre: "Rap",
    album: "The Slim Shady LP",
  },
  {
    id: 6,
    name: "Ionic Funk (20XXX Battle Music)",
    artist: "Machine Girl",
    image:
      "https://i.discogs.com/-i_wUzsLdHYCfrue1cXX-TiaLD6vk_zCbZuBYuN-UXo/rs:fit/g:sm/q:90/h:350/w:350/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTU0NjA1/NTgtMTM5MzkzOTA5/OS0yNzcyLmpwZWc.jpeg",
    genre: "Breakcore",
    album: "WLFGRL",
  },
  {
    id: 7,
    name: "Rhinestone Eyes",
    artist: "Gorillaz",
    image: "https://upload.wikimedia.org/wikipedia/en/d/d1/Plasticbeach452.jpg",
    genre: "Hip Hop",
    album: "Plastic Beach",
  },
  {
    id: 8,
    name: "Bodies",
    artist: "Drowning Pool",
    image: "https://upload.wikimedia.org/wikipedia/en/4/4f/DrowningpoolsinnerAP.JPG",
    genre: "Nu Metal",
    album: "Sinner",
  },
  {
    id: 9,
    name: "The Killing Moon",
    artist: "Echo & the Bunnymen",
    image: "https://upload.wikimedia.org/wikipedia/en/d/d3/Oceanrain.jpg",
    genre: "Post Punk",
    album: "Ocean Rain",
  },
  {
    id: 10,
    name: "Опиум для никого",
    artist: "Агата Кристи",
    image: "https://www.artlebedev.com/agata-kristi/opium/opium.jpg",
    genre: "Post Punk",
    album: "Oпиум",
  },
];
